{
    "openapi": "3.0.0",
    "info": {
        "title": "LimeSurvey REST API",
        "version": "1.0"
    },
    "paths": {
        "/rest/v1/question": {
            "get": {
                "tags": [
                    "Question"
                ],
                "summary": "Get question list",
                "description": "Get question list",
                "operationId": "ae270ed61c2473fae015fffbf95e2b9b",
                "parameters": [
                    {
                        "parameter": "surveyID",
                        "name": "surveyID",
                        "in": "query",
                        "description": "Survey id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "parameter": "groupID",
                        "name": "groupID",
                        "in": "query",
                        "description": "Group id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "parameter": "questionSettings",
                        "name": "questionSettings",
                        "in": "query",
                        "description": "Question settings",
                        "required": false,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    {
                        "parameter": "language",
                        "name": "language",
                        "in": "query",
                        "description": "Language",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/question_list"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Question"
                ],
                "summary": "Create question",
                "description": "Create question",
                "operationId": "b4503cdcbee337bf8982176f908a1fcf",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "surveyID",
                                    "groupID",
                                    "newQuestionTitle",
                                    "newQuestion"
                                ],
                                "properties": {
                                    "surveyID": {
                                        "type": "string"
                                    },
                                    "groupID": {
                                        "type": "string"
                                    },
                                    "importData": {
                                        "type": "string"
                                    },
                                    "importDataType": {
                                        "type": "string"
                                    },
                                    "newQuestionTitle": {
                                        "type": "string"
                                    },
                                    "newQuestion": {
                                        "type": "string"
                                    },
                                    "newQuestionHelp": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "surveyID": "1",
                                "groupID": "1",
                                "newQuestionTitle": "In what country do you live?",
                                "newQuestion": "In what country do you live?",
                                "newQuestionHelp": "In what country do you live?"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/response_status"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/rest/v1/question/{id}": {
            "get": {
                "tags": [
                    "Question"
                ],
                "summary": "Get question by id",
                "description": "Get question by id",
                "operationId": "d7bb06c56a4ec8f044b453db4582b139",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Question id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "parameter": "language",
                        "name": "language",
                        "in": "query",
                        "description": "Language",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/question_detail"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Question"
                ],
                "summary": "Update question by id",
                "description": "Update question by id",
                "operationId": "0b3b66c15e1026a081b1fbf30394e0a2",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Question id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "language",
                                    "questionData"
                                ],
                                "properties": {
                                    "language": {
                                        "type": "string"
                                    },
                                    "questionData": {
                                        "required": [],
                                        "properties": {
                                            "group_order": {
                                                "type": "string"
                                            },
                                            "randomization_group": {
                                                "type": "string"
                                            },
                                            "grelevance": {
                                                "type": "string"
                                            }
                                        },
                                        "type": "object"
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "language": "en",
                                "questionData": {
                                    "group_order": "1",
                                    "randomization_group": "1",
                                    "grelevance": "1"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Question"
                ],
                "summary": "Delete question by id",
                "description": "Delete question by id",
                "operationId": "8a5e79526903e3315d856772d3b2acb5",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Question id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/rest/v1/questionGroup": {
            "get": {
                "tags": [
                    "Question Group"
                ],
                "summary": "Get question group list",
                "description": "Get question group list",
                "operationId": "5b24b570d5cc3777ba697beacb5bf01e",
                "parameters": [
                    {
                        "parameter": "surveyID",
                        "name": "surveyID",
                        "in": "query",
                        "description": "Survey id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "parameter": "language",
                        "name": "language",
                        "in": "query",
                        "description": "Language",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/question_group_list"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "Question Group"
                ],
                "summary": "Create question group",
                "description": "Create question group",
                "operationId": "dd4be90189a7a3cde55e5b5aed060507",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "surveyID",
                                    "groupTitle",
                                    "groupDescription"
                                ],
                                "properties": {
                                    "surveyID": {
                                        "type": "string"
                                    },
                                    "groupTitle": {
                                        "type": "string"
                                    },
                                    "groupDescription": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "surveyID": "1",
                                "groupTitle": "Test Group",
                                "groupDescription": "This is a test group"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/rest/v1/questionGroup/{id}": {
            "get": {
                "tags": [
                    "Question Group"
                ],
                "summary": "Get question group by id",
                "description": "Get question group by id",
                "operationId": "45daa050b60dcdca9b44dac35a489345",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Question group id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "parameter": "groupSettings",
                        "name": "groupSettings[]",
                        "in": "query",
                        "description": "Group settings",
                        "required": false,
                        "allowReserved": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    {
                        "parameter": "language",
                        "name": "language",
                        "in": "query",
                        "description": "Language",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/question_group_detail"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "Question Group"
                ],
                "summary": "Update question group by id",
                "description": "Update question group by id",
                "operationId": "3d72f81399ec30032efba789865b6292",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Question group id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "language",
                                    "questionData"
                                ],
                                "properties": {
                                    "language": {
                                        "type": "string"
                                    },
                                    "questionData": {
                                        "required": [],
                                        "properties": {
                                            "group_order": {
                                                "type": "string"
                                            },
                                            "randomization_group": {
                                                "type": "string"
                                            },
                                            "grelevance": {
                                                "type": "string"
                                            }
                                        },
                                        "type": "object"
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "group_name": "Question group Two 2",
                                "description": "Question group Two 2 Desc",
                                "language": "en",
                                "questiongroupl10ns": {
                                    "en": {
                                        "group_name": "Question group 2 Two",
                                        "description": ""
                                    }
                                },
                                "order": "1",
                                "randomization_group": "",
                                "grelevance": "1"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "group_name": {
                                            "type": "boolean"
                                        },
                                        "description": {
                                            "type": "boolean"
                                        },
                                        "language": {
                                            "type": "boolean"
                                        },
                                        "questiongroupl10ns": {
                                            "properties": {
                                                "en": {
                                                    "properties": {
                                                        "group_name": {
                                                            "type": "string"
                                                        },
                                                        "description": {
                                                            "type": "string"
                                                        }
                                                    },
                                                    "type": "object"
                                                }
                                            },
                                            "type": "object"
                                        },
                                        "order": {
                                            "type": "string"
                                        },
                                        "randomization_group": {
                                            "type": "string"
                                        },
                                        "grelevance": {
                                            "type": "string"
                                        }
                                    },
                                    "type": "object"
                                },
                                "example": {
                                    "questiongroupl10ns": {
                                        "en": {
                                            "language": true,
                                            "group_name": true,
                                            "description": true
                                        }
                                    },
                                    "group_order": true,
                                    "randomization_group": true,
                                    "grelevance": true
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Question Group"
                ],
                "summary": "Delete question group by id",
                "description": "Delete question group by id",
                "operationId": "1a6cc1072390c835e826e52efd87aeae",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Question group id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/rest/v1/session": {
            "post": {
                "tags": [
                    "Session"
                ],
                "summary": "Create session token",
                "description": "Create session token",
                "operationId": "c34d5a4d94a347efaecb50cfd0693566",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "username",
                                    "password"
                                ],
                                "properties": {
                                    "username": {
                                        "description": "Username",
                                        "type": "string"
                                    },
                                    "password": {
                                        "description": "Password",
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success - returns session token",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "delete": {
                "tags": [
                    "Session"
                ],
                "summary": "Delete session",
                "description": "Delete session",
                "operationId": "00181f41c12bd1a510306b399ed124c0",
                "responses": {
                    "200": {
                        "description": "Success - session was deleted"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/rest/v1/siteSettings/{id}": {
            "get": {
                "tags": [
                    "Site Settings"
                ],
                "summary": "Get site settings",
                "description": "Get site settings",
                "operationId": "d4bff67730098c22afff9e0d3f90525f",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Setting id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/rest/v1/survey": {
            "post": {
                "tags": [
                    "Survey"
                ],
                "summary": "Create survey",
                "description": "Create survey",
                "operationId": "838606922cdf3aaa84c1bf8ed6d59a3f",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "required": [
                                    "surveyTitle",
                                    "surveyLanguage"
                                ],
                                "properties": {
                                    "surveyID": {
                                        "type": "string"
                                    },
                                    "surveyTitle": {
                                        "type": "string"
                                    },
                                    "surveyLanguage": {
                                        "type": "string"
                                    },
                                    "format": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            },
                            "example": {
                                "surveyID": "1",
                                "surveyTitle": "Test Survey",
                                "surveyLanguage": "en",
                                "format": null
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success - returns survey id",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "integer"
                                },
                                "example": 263491
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        },
        "/rest/v1/survey/{id}": {
            "get": {
                "tags": [
                    "Survey"
                ],
                "summary": "Get survey by id",
                "description": "Get survey by id",
                "operationId": "ce34922b77184455f19d5163f5ab8612",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Survey id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "parameter": "surveySettings",
                        "name": "surveySettings[]",
                        "in": "query",
                        "description": "Survey settings",
                        "required": false,
                        "allowReserved": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Survey"
                ],
                "summary": "Delete survey by id",
                "description": "Delete survey by id",
                "operationId": "0703065e5b8a313d47a7cfcc60590203",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Survey id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not found"
                    }
                },
                "security": [
                    {
                        "bearerAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "question_detail": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "parent_qid": {
                        "type": "string"
                    },
                    "sid": {
                        "type": "string"
                    },
                    "gid": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "preg": {
                        "type": "string"
                    },
                    "other": {
                        "type": "string"
                    },
                    "mandatory": {
                        "type": "string"
                    },
                    "encrypted": {
                        "type": "string"
                    },
                    "question_order": {
                        "type": "string"
                    },
                    "scale_id": {
                        "type": "string"
                    },
                    "same_default": {
                        "type": "string"
                    },
                    "relevance": {
                        "type": "string"
                    },
                    "question_theme_name": {
                        "type": "string"
                    },
                    "modulename": {
                        "type": "string"
                    },
                    "same_script": {
                        "type": "string"
                    },
                    "available_answers": {
                        "type": "string"
                    },
                    "subquestions": {
                        "type": "string"
                    },
                    "attributes": {
                        "properties": {
                            "cssclass": {
                                "type": "string"
                            },
                            "display_rows": {
                                "type": "string"
                            },
                            "em_validation_q": {
                                "type": "string"
                            },
                            "hidden": {
                                "type": "string"
                            },
                            "hide_tip": {
                                "type": "string"
                            },
                            "input_size": {
                                "type": "string"
                            },
                            "maximum_chars": {
                                "type": "string"
                            },
                            "page_break": {
                                "type": "string"
                            },
                            "random_group": {
                                "type": "string"
                            },
                            "statistics_graphtype": {
                                "type": "string"
                            },
                            "statistics_showgraph": {
                                "type": "string"
                            },
                            "text_input_width": {
                                "type": "string"
                            },
                            "time_limit": {
                                "type": "string"
                            },
                            "time_limit_action": {
                                "type": "string"
                            },
                            "time_limit_disable_next": {
                                "type": "string"
                            },
                            "time_limit_disable_prev": {
                                "type": "string"
                            },
                            "time_limit_message_delay": {
                                "type": "string"
                            },
                            "time_limit_message_style": {
                                "type": "string"
                            },
                            "time_limit_timer_style": {
                                "type": "string"
                            },
                            "time_limit_warning": {
                                "type": "string"
                            },
                            "time_limit_warning_2": {
                                "type": "string"
                            },
                            "time_limit_warning_2_display_time": {
                                "type": "string"
                            },
                            "time_limit_warning_2_style": {
                                "type": "string"
                            },
                            "time_limit_warning_display_time": {
                                "type": "string"
                            },
                            "time_limit_warning_style": {
                                "type": "string"
                            }
                        },
                        "type": "object"
                    },
                    "attributes_lang": {
                        "properties": {
                            "em_validation_q_tip": {
                                "type": "string"
                            },
                            "time_limit_countdown_message": {
                                "type": "string"
                            },
                            "time_limit_message": {
                                "type": "string"
                            },
                            "time_limit_warning_2_message": {
                                "type": "string"
                            },
                            "time_limit_warning_message": {
                                "type": "string"
                            }
                        },
                        "type": "object"
                    },
                    "answeroptions": {
                        "type": "string"
                    },
                    "defaultvalue": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "qid": "1",
                    "parent_qid": "0",
                    "sid": "712896",
                    "gid": "1",
                    "type": "T",
                    "title": "G01Q01",
                    "preg": "",
                    "other": "N",
                    "mandatory": "N",
                    "encrypted": "N",
                    "question_order": "1",
                    "scale_id": "0",
                    "same_default": "0",
                    "relevance": "1",
                    "question_theme_name": "longfreetext",
                    "modulename": null,
                    "same_script": "0",
                    "available_answers": "No available answers",
                    "subquestions": "No available answers",
                    "attributes": {
                        "cssclass": "",
                        "display_rows": "",
                        "em_validation_q": "",
                        "hidden": "0",
                        "hide_tip": "0",
                        "input_size": "",
                        "maximum_chars": "",
                        "page_break": "0",
                        "random_group": "",
                        "statistics_graphtype": "0",
                        "statistics_showgraph": "1",
                        "text_input_width": "",
                        "time_limit": "",
                        "time_limit_action": "1",
                        "time_limit_disable_next": "0",
                        "time_limit_disable_prev": "0",
                        "time_limit_message_delay": "",
                        "time_limit_message_style": "",
                        "time_limit_timer_style": "",
                        "time_limit_warning": "",
                        "time_limit_warning_2": "",
                        "time_limit_warning_2_display_time": "",
                        "time_limit_warning_2_style": "",
                        "time_limit_warning_display_time": "",
                        "time_limit_warning_style": ""
                    },
                    "attributes_lang": {
                        "em_validation_q_tip": "",
                        "time_limit_countdown_message": "",
                        "time_limit_message": "",
                        "time_limit_warning_2_message": "",
                        "time_limit_warning_message": ""
                    },
                    "answeroptions": "No available answer options",
                    "defaultvalue": null
                }
            },
            "question_list": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/question_list_item"
                },
                "example": [
                    {
                        "id": "1",
                        "question": "Question 1",
                        "help": "This is a question help text.",
                        "language": "en",
                        "qid": "1",
                        "parent_qid": "0",
                        "sid": "712896",
                        "type": "T",
                        "title": "G01Q01",
                        "preg": "",
                        "other": "N",
                        "mandatory": "N",
                        "encrypted": "N",
                        "question_order": "1",
                        "scale_id": "0",
                        "same_default": "0",
                        "question_theme_name": "longfreetext",
                        "modulename": null,
                        "gid": "1",
                        "relevance": "1",
                        "same_script": "0"
                    }
                ]
            },
            "question_list_item": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "question": {
                        "type": "string"
                    },
                    "help": {
                        "type": "string"
                    },
                    "language": {
                        "type": "string"
                    },
                    "qid": {
                        "type": "string"
                    },
                    "parent_qid": {
                        "type": "string"
                    },
                    "sid": {
                        "type": "string"
                    },
                    "type": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "preg": {
                        "type": "string"
                    },
                    "other": {
                        "type": "string"
                    },
                    "mandatory": {
                        "type": "string"
                    },
                    "encrypted": {
                        "type": "string"
                    },
                    "question_order": {
                        "type": "string"
                    },
                    "scale_id": {
                        "type": "string"
                    },
                    "same_default": {
                        "type": "string"
                    },
                    "question_theme_name": {
                        "type": "string"
                    },
                    "modulename": {
                        "type": "string"
                    },
                    "gid": {
                        "type": "string"
                    },
                    "relevance": {
                        "type": "string"
                    },
                    "same_script": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "id": "1",
                    "question": "Question 1",
                    "help": "This is a question help text.",
                    "language": "en",
                    "qid": "1",
                    "parent_qid": "0",
                    "sid": "712896",
                    "type": "T",
                    "title": "G01Q01",
                    "preg": "",
                    "other": "N",
                    "mandatory": "N",
                    "encrypted": "N",
                    "question_order": "1",
                    "scale_id": "0",
                    "same_default": "0",
                    "question_theme_name": "longfreetext",
                    "modulename": null,
                    "gid": "1",
                    "relevance": "1",
                    "same_script": "0"
                }
            },
            "question_group_detail": {
                "properties": {
                    "gid": {
                        "type": "string"
                    },
                    "sid": {
                        "type": "string"
                    },
                    "group_order": {
                        "type": "string"
                    },
                    "randomization_group": {
                        "type": "string"
                    },
                    "grelevance": {
                        "type": "string"
                    },
                    "group_name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "gid": "1",
                    "sid": "712896",
                    "group_order": "0",
                    "randomization_group": "",
                    "grelevance": "",
                    "group_name": "Question group 1",
                    "description": "Description of group 1"
                }
            },
            "question_group_list": {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/question_group_list_item"
                },
                "example": [
                    {
                        "id": "1",
                        "gid": "1",
                        "sid": "712896",
                        "group_order": "0",
                        "randomization_group": "",
                        "grelevance": "",
                        "group_name": "Question group 1",
                        "description": "",
                        "language": "en"
                    }
                ]
            },
            "question_group_list_item": {
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "gid": {
                        "type": "string"
                    },
                    "sid": {
                        "type": "string"
                    },
                    "group_order": {
                        "type": "string"
                    },
                    "randomization_group": {
                        "type": "string"
                    },
                    "grelevance": {
                        "type": "string"
                    },
                    "group_name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "language": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "id": "1",
                    "gid": "1",
                    "sid": "712896",
                    "group_order": "0",
                    "randomization_group": "",
                    "grelevance": "",
                    "group_name": "Question group 1",
                    "description": "",
                    "language": "en"
                }
            },
            "response_status": {
                "properties": {
                    "status": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "status": "Error: Invalid question id"
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "name": "Bearer Auth",
                "in": "header",
                "scheme": "bearer"
            }
        }
    }
}